dist: bionic

language: go

go:
  - 1.15

services:
  - docker

stages:
  - name: release
    if: branch = master

jobs:
  include:
    - stage: release
      os: linux
      dist: bionic
      before_install:
        - sudo apt-get -y install libseccomp-dev
        - go get -t -v ./...
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: 
        - go build -o vorteil github.com/vorteil/vorteil/cmd/vorteil 
        - GOOS=windows go build -o vorteil.exe github.com/vorteil/vorteil/cmd/vorteil
        - docker pull hello-world
        - sudo apt install containerd
        - sudo ctr images pull docker.io/library/hello-world:latest
        - sudo usermod -a -G root,docker $(whoami)
        - go test -timeout 30s -coverprofile c.out ./...
        - zip vorteil_windows-x86.zip vorteil.exe
        - tar -zcvf vorteil_linux-x86.tar.gz vorteil
      after_success:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -r $CC_TEST_REPORTER_ID
      deploy:
        provider: releases
        api_key: $GTOKEN
        file:
          - vorteil_windows-x86.zip
          - vorteil_linux-x86.tar.gz
        skip_cleanup: true
        draft: true
        on:
          tags: true      
    - stage: release
      os: osx
      osx_image: "xcode11.3"
      before_install:
        - go get -t -v ./...
      before_script:
        - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then export KEY_CHAIN=build.keychain; fi;
        - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then export CERTIFICATE_P12=certificate.p12; fi;
        - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then echo $OSX_P12_CERT | base64 --decode > $CERTIFICATE_P12; fi;
        - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then security create-keychain -p travis $KEY_CHAIN; fi;
        - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then security default-keychain -s $KEY_CHAIN; fi;
        - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then security unlock-keychain -p travis $KEY_CHAIN; fi;
        - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then security import $CERTIFICATE_P12 -k $KEY_CHAIN -P $OSX_P12_PW -T /usr/bin/codesign; fi;
        - |-
          if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then security set-key-partition-list -S apple-tool:,apple: -s -k travis $KEY_CHAIN; fi;
        - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then rm -fr *.p12; fi;
      script:
        - go build -o vorteil github.com/vorteil/vorteil/cmd/vorteil
        - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then codesign -s $OSX_APP_SIGN_ID -v --timestamp --options runtime vorteil; fi;
        - mkdir -p build && mv vorteil build/
        - hdiutil create ./vorteil_darwin-x86.dmg -ov -volname "Vorteil CLI" -fs HFS+ -srcfolder ./build/
        - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then codesign --force --deep -s $OSX_APP_SIGN_ID -v --timestamp --options runtime vorteil_darwin-x86.dmg; fi;
        - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then xcrun altool --notarize-app --file $(pwd)/vorteil_darwin-x86.dmg --username $OSX_NOTARIZE_USERNAME --primary-bundle-id com.vorteil.cli -p $OSX_NOTARIZE_PW -- >> /dev/null; fi;
        - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then for ((i=1;i<=30;i+=1)); do xcrun stapler staple $(pwd)/vorteil_darwin-x86.dmg >> /dev/null; if [ $? = 65 ]; then echo "Waiting for notarization to complete..." && sleep 10; fi; done; fi;
      deploy:
        provider: releases
        api_key: $GTOKEN
        file:
          - vorteil_darwin-x86.dmg
        skip_cleanup: true
        draft: true
        on: 
          tags: true
